name: CI - Simple java Docker App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: [self-hosted]

    steps:
    - name: Checkout source code
      uses: actions/checkout@v3

    - name: Complite java
      run: javac App.java

    - name: Build Docker image
      run: docker build -t simple-java-app .

  deploy:
    runs-on: [self-hosted]
    needs: build

    steps:
    - name: Run Docker container
      runs:
        docker stop simple-java-app || true
        docker rm simple-java-app || true
        docker run -d -p 8888:8888 --name simple-java-app simple-java-app

    - name: verify container is running
      run:
        sleep 2
        curl -f http://localhost:8888 || (echo "App đi not start!" && exit 1)
