name: CI - Department service2

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: [self-hosted]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Compile mvn
        run: mvn clean package -DskipTests

      - name: Build Docker image
        run: docker build -t department-service:v1 .

  deploy:
    env:
      APP_PORT: 8081
      DB_URL: jdbc:mysql://localhost:3309/microservice?createDatabaseIfNotExist=true&characterEncoding=UTF-8&serverTimezone=UTC
      DB_USERNAME: root
      DB_PASSWORD: Password123@
    runs-on: [self-hosted]
    needs: build

    steps:
      - name: Stop and Remove Existing Containers
        run: docker compose down || true # Ignore errors if no containers are running

      - name: Run with Docker Compose
        run: docker compose up -d
